In [63]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [64]:
data = pd.read_excel('aguasfeo.xlsx')
data.describe

<bound method NDFrame.describe of          Sabor  Tamano Hielo  Calificacion
0      Naranja   chica    si           9.5
1      Naranja   chica    no           7.0
2      Naranja  grande    si          10.0
3      Naranja  grande    no           7.5
4         Coco   chica    si           7.5
5         Coco   chica    no           6.0
6         Coco  grande    si           8.0
7         Coco  grande    no           7.0
8       Kahlua   chica    si           9.0
9       Kahlua   chica    no           7.0
10      Kahlua  grande    si           9.5
11      Kahlua  grande    no           7.5
12  Fresa-pina   chica    si           8.5
13  Fresa-pina   chica    no           7.0
14  Fresa-pina  grande    si           9.0
15  Fresa-pina  grande    no           6.0
16     Sandia    chica    si           7.0
17     Sandia    chica    no           5.0
18     Sandia   grande    si           7.5
19     Sandia   grande    no           6.0>

In [65]:
#remplazando los valores de las variables cualitativas por valores numericos
tamano = data['Tamano'].replace('chica', 0).replace('grande', 1)
hielo = data['Hielo'].replace('no', 0).replace('si', 1)

In [66]:
data[data['Sabor']=='Naranja']

     Sabor  Tamano Hielo  Calificacion
0  Naranja   chica    si           9.5
1  Naranja   chica    no           7.0
2  Naranja  grande    si          10.0
3  Naranja  grande    no           7.5

In [67]:
data['Naranja'] = np.where(data['Sabor'] == 'Naranja', 1, 0)
data['Coco'] = np.where(data['Sabor'] == 'Coco', 1, 0)
data['Kahlua'] = np.where(data['Sabor'] == 'Kahlua', 1, 0)
data['Fresa_pina'] = np.where(data['Sabor'] == 'Fresa-pina', 1, 0)
data['Sandia'] = np.where(data['Sabor'] == 'Sandia', 1, 0)

In [68]:
data.head()

,Sabor,Tamano,Hielo,Calificacion,Naranja,Coco,Kahlua,Fresa_pina,Sandia
0,Naranja,chica,si,9.5,1,0,0,0,0
1,Naranja,chica,no,7.0,1,0,0,0,0
2,Naranja,grande,si,10.0,1,0,0,0,0
3,Naranja,grande,no,7.5,1,0,0,0,0
4,Coco,chica,si,7.5,0,1,0,0,0

In [69]:
from sklearn.linear_model import LinearRegression

X = np.column_stack((
    tamano,
    hielo,
    data['Naranja'],
    data['Coco'],
    data['Kahlua'],
    data['Fresa_pina'],
    data['Sandia']
))
y = data['Calificacion']

lr = LinearRegression()
lr.fit(X, y)

pred = lr.predict(X)

In [80]:
import statsmodels.api as sm

# Agregar constante para el intercepto
X_OLS = sm.add_constant(X)

# Modelo OLS
modelo_OLS = sm.OLS(y, X_OLS)

# Ajustar modelo
resultado_OLS = modelo_OLS.fit()

# Ver resultados completos
print(resultado_OLS.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:           Calificacion   R-squared:                       0.933
Model:                            OLS   Adj. R-squared:                  0.902
Method:                 Least Squares   F-statistic:                     30.17
Date:                Thu, 03 Sep 2026   Prob (F-statistic):           6.63e-07
Time:                        17:45:50   Log-Likelihood:                -6.6960
No. Observations:                  20   AIC:                             27.39
Df Residuals:                      13   BIC:                             34.36
Df Model:                           6
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          5.3125      0.135     39.240      0.000       5.020       5.605
x1             0.4500      0.188      2.399      0.032       0.045       0.855
x2             1.9500      0.188     10.395      0.000       1.545       2.355
x3             0.6125      0.190      3.232      0.007       0.203       1.022
x4             1.1125      0.190      5.869      0.000       0.703       1.522
x5             1.7375      0.190      9.167      0.000       1.328       2.147
x6             1.9875      0.190     10.486      0.000       1.578       2.397
x7            -0.1375      0.190     -0.725      0.481      -0.547       0.272
==============================================================================
Omnibus:                        1.962   Durbin-Watson:                   2.146
Prob(Omnibus):                  0.375   Jarque-Bera (JB):                0.646
Skew:                          -0.349   Prob(JB):                        0.724
Kurtosis:                       3.536   Cond. No.                     9.95e+15
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 3.6e-31. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.

In [81]:
print('Coeficientes:')
print(resultado_OLS.params)

print('Errores estandar:')
print(resultado_OLS.bse)

print('Estadisticos t:')
print(resultado_OLS.tvalues)

print('P-values:')
print(resultado_OLS.pvalues)

Coeficientes:
const    5.3125
x1       0.4500
x2       1.9500
x3       0.6125
x4       1.1125
x5       1.7375
x6       1.9875
x7      -0.1375
dtype: float64
Errores estandar:
const    0.135386
x1       0.187596
x2       0.187596
x3       0.189540
x4       0.189540
x5       0.189540
x6       0.189540
x7       0.189540
dtype: float64
Estadisticos t:
const    39.239701
x1        2.398770
x2       10.394671
x3        3.231505
x4        5.869468
x5        9.166922
x6       10.485903
x7       -0.725440
dtype: float64
P-values:
const    6.865475e-15
x1       3.215896e-02
x2       1.146171e-07
x3       6.557577e-03
x4       5.505785e-05
x5       4.888182e-07
x6       1.034724e-07
x7       4.810381e-01
dtype: float64

In [70]:
print('Intercepto:', lr.intercept_)
print('Coeficientes:', lr.coef_)
print('R2:', lr.score(X, y))

Intercepto: 5.175000000000001
Coeficientes: [0.45  1.95  2.125 0.75  1.875 1.25  0.   ]
R2: 0.9329915781764921

In [71]:
# Errores
error = y - pred

# RSS
RSS = np.sum(error**2)

# Numero de datos
n = len(y)

# Numero de parametros
p = X.shape[1] + 1

# Varianza del error
sigma2 = RSS / (n-p)

print('RSS:', RSS)
print('Varianza del error:', sigma2)

RSS: 2.2874999999999988
Varianza del error: 0.1906249999999999

In [72]:
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import OneHotEncoder

In [73]:
OrdinalEncoder?
OneHotEncoder?

Init signature:
OneHotEncoder(
    *,
    categories='auto',
    drop=None,
    sparse_output=True,
    dtype=<class 'numpy.float64'>,
    handle_unknown='error',
    min_frequency=None,
    max_categories=None,
    feature_name_combiner='concat',
)
Docstring:
Encode categorical features as a one-hot numeric array.

The input to this transformer should be an array-like of integers or
strings, denoting the values taken on by categorical (discrete) features.
The features are encoded using a one-hot (aka 'one-of-K' or 'dummy')
encoding scheme. This creates a binary column for each category and
returns a sparse matrix or dense array (depending on the ``sparse_output``
parameter).

By default, the encoder derives the categories based on the unique values
in each feature. Alternatively, you can also specify the `categories`
manually.

This encoding is needed for feeding categorical data to many scikit-learn
estimators, notably linear models and SVMs with the standard kernels.

Note: a one-hot encoding of y labels should use a LabelBinarizer
instead.

Read more in the :ref:`User Guide <preprocessing_categorical_features>`.
For a comparison of different encoders, refer to:
:ref:`sphx_glr_auto_examples_preprocessing_plot_target_encoder.py`.

Parameters
----------
categories : 'auto' or a list of array-like, default='auto'
    Categories (unique values) per feature:

    - 'auto' : Determine categories automatically from the training data.
    - list : ``categories[i]`` holds the categories expected in the ith
      column. The passed categories should not mix strings and numeric
      values within a single feature, and should be sorted in case of
      numeric values.

    The used categories can be found in the ``categories_`` attribute.

    .. versionadded:: 0.20

drop : {'first', 'if_binary'} or an array-like of shape (n_features,),             default=None
    Specifies a methodology to use to drop one of the categories per
    feature. This is useful in situations where perfectly collinear
    features cause problems, such as when feeding the resulting data
    into an unregularized linear regression model.

    However, dropping one category breaks the symmetry of the original
    representation and can therefore induce a bias in downstream models,
    for instance for penalized linear classification or regression models.

    - None : retain all features (the default).
    - 'first' : drop the first category in each feature. If only one
      category is present, the feature will be dropped entirely.
    - 'if_binary' : drop the first category in each feature with two
      categories. Features with 1 or more than 2 categories are
      left intact.
    - array : ``drop[i]`` is the category in feature ``X[:, i]`` that
      should be dropped.

    When `max_categories` or `min_frequency` is configured to group
    infrequent categories, the dropping behavior is handled after the
    grouping.

    .. versionadded:: 0.21
       The parameter `drop` was added in 0.21.

    .. versionchanged:: 0.23
       The option `drop='if_binary'` was added in 0.23.

    .. versionchanged:: 1.1
        Support for dropping infrequent categories.

sparse_output : bool, default=True
    When ``True``, it returns a SciPy sparse matrix/array
    in "Compressed Sparse Row" (CSR) format.

    .. versionadded:: 1.2
       `sparse` was renamed to `sparse_output`

dtype : number type, default=np.float64
    Desired dtype of output.

handle_unknown : {'error', 'ignore', 'infrequent_if_exist', 'warn'},                      default='error'
    Specifies the way unknown categories are handled during :meth:`transform`.

    - 'error' : Raise an error if an unknown category is present during transform.
    - 'ignore' : When an unknown category is encountered during
      transform, the resulting one-hot encoded columns for this feature
      will be all zeros. In the inverse transform, an unknown category
      will be denoted as None.
    - 'infrequent_if_exist' : When an unknown category is encountered
      during transform, the resulting one-hot encoded columns for this
      feature will map to the infrequent category if it exists. The
      infrequent category will be mapped to the last position in the
      encoding. During inverse transform, an unknown category will be
      mapped to the category denoted `'infrequent'` if it exists. If the
      `'infrequent'` category does not exist, then :meth:`transform` and
      :meth:`inverse_transform` will handle an unknown category as with
      `handle_unknown='ignore'`. Infrequent categories exist based on
      `min_frequency` and `max_categories`. Read more in the
      :ref:`User Guide <encoder_infrequent_categories>`.
    - 'warn' : When an unknown category is encountered during transform
      a warning is issued, and the encoding then proceeds as described for
      `handle_unknown="infrequent_if_exist"`.

    .. versionchanged:: 1.1
        `'infrequent_if_exist'` was added to automatically handle unknown
        categories and infrequent categories.

    .. versionadded:: 1.6
       The option `"warn"` was added in 1.6.

min_frequency : int or float, default=None
    Specifies the minimum frequency below which a category will be
    considered infrequent.

    - If `int`, categories with a smaller cardinality will be considered
      infrequent.

    - If `float`, categories with a smaller cardinality than
      `min_frequency * n_samples`  will be considered infrequent.

    .. versionadded:: 1.1
        Read more in the :ref:`User Guide <encoder_infrequent_categories>`.

max_categories : int, default=None
    Specifies an upper limit to the number of output features for each input
    feature when considering infrequent categories. If there are infrequent
    categories, `max_categories` includes the category representing the
    infrequent categories along with the frequent categories. If `None`,
    there is no limit to the number of output features.

    .. versionadded:: 1.1
        Read more in the :ref:`User Guide <encoder_infrequent_categories>`.

feature_name_combiner : "concat" or callable, default="concat"
    Callable with signature `def callable(input_feature, category)` that returns a
    string. This is used to create feature names to be returned by
    :meth:`get_feature_names_out`.

    `"concat"` concatenates encoded feature name and category with
    `feature + "_" + str(category)`.E.g. feature X with values 1, 6, 7 create
    feature names `X_1, X_6, X_7`.

    .. versionadded:: 1.3

Attributes
----------
categories_ : list of arrays
    The categories of each feature determined during fitting
    (in order of the features in X and corresponding with the output
    of ``transform``). This includes the category specified in ``drop``
    (if any).

drop_idx_ : array of shape (n_features,)
    - ``drop_idx_[i]`` is the index in ``categories_[i]`` of the category
      to be dropped for each feature.
    - ``drop_idx_[i] = None`` if no category is to be dropped from the
      feature with index ``i``, e.g. when `drop='if_binary'` and the
      feature isn't binary.
    - ``drop_idx_ = None`` if all the transformed features will be
      retained.

    If infrequent categories are enabled by setting `min_frequency` or
    `max_categories` to a non-default value and `drop_idx[i]` corresponds
    to an infrequent category, then the entire infrequent category is
    dropped.

    .. versionchanged:: 0.23
       Added the possibility to contain `None` values.

infrequent_categories_ : list of ndarray
    Defined only if infrequent categories are enabled by setting
    `min_frequency` or `max_categories` to a non-default value.
    `infrequent_categories_[i]` are the infrequent categories for feature
    `i`. If the feature `i` has no infrequent categories
    `infrequent_categories_[i]` is None.

    .. versionadded:: 1.1

n_features_in_ : int
    Number of features seen during :term:`fit`.

    .. versionadded:: 1.0

feature_names_in_ : ndarray of shape (`n_features_in_`,)
    Names of features seen during :term:`fit`. Defined only when `X`
    has feature names that are all strings.

    .. versionadded:: 1.0

feature_name_combiner : callable or None
    Callable with signature `def callable(input_feature, category)` that returns a
    string. This is used to create feature names to be returned by
    :meth:`get_feature_names_out`.

    .. versionadded:: 1.3

See Also
--------
OrdinalEncoder : Performs an ordinal (integer)
  encoding of the categorical features.
TargetEncoder : Encodes categorical features using the target.
sklearn.feature_extraction.DictVectorizer : Performs a one-hot encoding of
  dictionary items (also handles string-valued features).
sklearn.feature_extraction.FeatureHasher : Performs an approximate one-hot
  encoding of dictionary items or strings.
LabelBinarizer : Binarizes labels in a one-vs-all
  fashion.
MultiLabelBinarizer : Transforms between iterable of
  iterables and a multilabel format, e.g. a (samples x classes) binary
  matrix indicating the presence of a class label.

Examples
--------
Given a dataset with two features, we let the encoder find the unique
values per feature and transform the data to a binary one-hot encoding.

>>> from sklearn.preprocessing import OneHotEncoder

One can discard categories not seen during `fit`:

>>> enc = OneHotEncoder(handle_unknown='ignore')
>>> X = [['Male', 1], ['Female', 3], ['Female', 2]]
>>> enc.fit(X)
OneHotEncoder(handle_unknown='ignore')
>>> enc.categories_
[array(['Female', 'Male'], dtype=object), array([1, 2, 3], dtype=object)]
>>> enc.transform([['Female', 1], ['Male', 4]]).toarray()
array([[1., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0.]])
>>> enc.inverse_transform([[0, 1, 1, 0, 0], [0, 0, 0, 1, 0]])
array([['Male', 1],
       [None, 2]], dtype=object)
>>> enc.get_feature_names_out(['gender', 'group'])
array(['gender_Female', 'gender_Male', 'group_1', 'group_2', 'group_3'], ...)

One can always drop the first column for each feature:

>>> drop_enc = OneHotEncoder(drop='first').fit(X)
>>> drop_enc.categories_
[array(['Female', 'Male'], dtype=object), array([1, 2, 3], dtype=object)]
>>> drop_enc.transform([['Female', 1], ['Male', 2]]).toarray()
array([[0., 0., 0.],
       [1., 1., 0.]])

Or drop a column for feature only having 2 categories:

>>> drop_binary_enc = OneHotEncoder(drop='if_binary').fit(X)
>>> drop_binary_enc.transform([['Female', 1], ['Male', 2]]).toarray()
array([[0., 1., 0., 0.],
       [1., 0., 1., 0.]])

One can change the way feature names are created.

>>> def custom_combiner(feature, category):
...     return str(feature) + "_" + type(category).__name__ + "_" + str(category)
>>> custom_fnames_enc = OneHotEncoder(feature_name_combiner=custom_combiner).fit(X)
>>> custom_fnames_enc.get_feature_names_out()
array(['x0_str_Female', 'x0_str_Male', 'x1_int_1', 'x1_int_2', 'x1_int_3'],
      dtype=object)

Infrequent categories are enabled by setting `max_categories` or `min_frequency`.

>>> import numpy as np
>>> X = np.array([["a"] * 5 + ["b"] * 20 + ["c"] * 10 + ["d"] * 3], dtype=object).T
>>> ohe = OneHotEncoder(max_categories=3, sparse_output=False).fit(X)
>>> ohe.infrequent_categories_
[array(['a', 'd'], dtype=object)]
>>> ohe.transform([["a"], ["b"]])
array([[0., 0., 1.],
       [1., 0., 0.]])
File:           /opt/anaconda3/lib/python3.14/site-packages/sklearn/preprocessing/_encoders.py
Type:           type
Subclasses:

In [74]:
# Tamano
encoder_tamano = OrdinalEncoder(categories=[['chica','grande']])
tamano = encoder_tamano.fit_transform(data[['Tamano']])

# Hielo
encoder_hielo = OrdinalEncoder(categories=[['no','si']])
hielo = encoder_hielo.fit_transform(data[['Hielo']])

# Sabor
encoder_sabor = OneHotEncoder(sparse_output=False)
sabores = encoder_sabor.fit_transform(data[['Sabor']])

In [75]:
X = np.column_stack((tamano, hielo, sabores))

y = data['Calificacion']
print(X)
print(y)

[[0. 1. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [1. 1. 0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0. 1. 0.]
 [0. 1. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0. 0.]
 [1. 0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [1. 1. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 1. 0. 0.]
 [0. 1. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [1. 1. 0. 1. 0. 0. 0.]
 [1. 0. 0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]]
0      9.5
1      7.0
2     10.0
3      7.5
4      7.5
5      6.0
6      8.0
7      7.0
8      9.0
9      7.0
10     9.5
11     7.5
12     8.5
13     7.0
14     9.0
15     6.0
16     7.0
17     5.0
18     7.5
19     6.0
Name: Calificacion, dtype: float64

In [76]:
lr = LinearRegression()
lr.fit(X,y)

print('Intercepto:', lr.intercept_)
print('Coeficientes:', lr.coef_)
print('R2:', lr.score(X,y))

Intercepto: 6.375
Coeficientes: [ 0.45   1.95  -0.45   0.05   0.675  0.925 -1.2  ]
R2: 0.9329915781764921

In [83]:
import statsmodels.api as sm
# Agregar columna de unos para beta 0
X = sm.add_constant(X)


# REGRESION OLS
modelo = sm.OLS(y, X)

resultado = modelo.fit()


# Resultados
print(resultado.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:           Calificacion   R-squared:                       0.933
Model:                            OLS   Adj. R-squared:                  0.902
Method:                 Least Squares   F-statistic:                     30.17
Date:                Thu, 03 Sep 2026   Prob (F-statistic):           6.63e-07
Time:                        17:48:24   Log-Likelihood:                -6.6960
No. Observations:                  20   AIC:                             27.39
Df Residuals:                      13   BIC:                             34.36
Df Model:                           6
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          5.3125      0.135     39.240      0.000       5.020       5.605
x1             0.4500      0.188      2.399      0.032       0.045       0.855
x2             1.9500      0.188     10.395      0.000       1.545       2.355
x3             0.6125      0.190      3.232      0.007       0.203       1.022
x4             1.1125      0.190      5.869      0.000       0.703       1.522
x5             1.7375      0.190      9.167      0.000       1.328       2.147
x6             1.9875      0.190     10.486      0.000       1.578       2.397
x7            -0.1375      0.190     -0.725      0.481      -0.547       0.272
==============================================================================
Omnibus:                        1.962   Durbin-Watson:                   2.146
Prob(Omnibus):                  0.375   Jarque-Bera (JB):                0.646
Skew:                          -0.349   Prob(JB):                        0.724
Kurtosis:                       3.536   Cond. No.                     9.95e+15
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 3.6e-31. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.

In [87]:
print(resultado.params)

const    5.3125
x1       0.4500
x2       1.9500
x3       0.6125
x4       1.1125
x5       1.7375
x6       1.9875
x7      -0.1375
dtype: float64